spring.application.name=esiBuy

spring.config.import=optional:file:.env[.properties]
spring.mongodb.uri=${MONGODB_URI}

app.security.allow-development=true
# Esto permite que cualquier usuario pueda crear productos sin necesidad de estar autenticado.
