spring.application.name=esiBuy
spring.mongodb.uri=${MONGODB_URI}

#spring.config.import=optional:file:.env[.properties]
spring.config.import=optional:file:.env[.properties],optional:file:./Back_esiBuy/.env[.properties]

#spring.data.mongodb.auto-index-creation=true
