spring.application.name=esiBuy
spring.mongodb.uri=${MONGODB_URI}
app.password-reset-url=${PASSWORD_RESET_URL:http://localhost:5173/reset-password}

#spring.config.import=optional:file:.env[.properties]
spring.config.import=optional:file:.env[.properties],optional:file:./Back_esiBuy/.env[.properties]

#spring.data.mongodb.auto-index-creation=true

app.password-reset-url=http://localhost:4200/reset-password?token=